name: Devastation Podcast
description: Devastation Podcast - Το Podcast για Developers
url: http://devastation.tv

markdown: redcarpet
permalink: pretty
highlighter: null

exclude: ["node_modules", "gulpfile.js", "package.json"]

gems:
  - jekyll-feed
