name: Devastation Podcast
description: Devastation Podcast - Το Podcast για Developers
url: http://devastation.tv
managerName: Kostas Bariotis
managerEmail: konmpar@gmail.com
squareLogo: /img/thess.jpg
organizationName: Devastation Podcast
podcastSubtitle: Devastation Podcast - Το Podcast για Developers

markdown: redcarpet
permalink: pretty
highlighter: null

exclude: ["node_modules", "gulpfile.js", "package.json"]

gems:
  - jekyll-sitemap
